version: '2'
services:
  elasticsearch:
    build: elasticsearch/
    image: initiumlab/analytics-elasticsearch:5.5.2-1
    ports:
      - "9200:9200"
      - "9300:9300"

  curator:
    build: curator/
    image: initiumlab/analytics-elasticsearch-curator:5.2.0-1
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      MAX_INDEX_AGE: 2
      INDEX_PREFIX: logstash

  logstash:
    build: logstash/
    image: initiumlab/analytics-logstash:5.5.2-1
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/config/31-output-stdout.conf:/etc/logstash/conf.d/31-output-stdout.conf
      - ./logs:/logs
    ports:
      - "5000:5000"
      - "5044:5044"
      - "12201:12201/udp"
    links:
      - elasticsearch

  kibana:
    build: kibana/
    image: initiumlab/analytics-kibana:5.5.2-1
    volumes:
      - ./kibana/config/:/opt/kibana/config/
      - ./data:/usr/share/elasticsearch/data
    ports:
      - "5601:5601"
    links:
      - elasticsearch
