version: '2'
services:
  elasticsearch:
    build: logstash/
    image: initiumlab/analytics-elasticsearch:2.3.4-1
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    build: logstash/
    image: initiumlab/analytics-logstash:2.3.4-1
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    links:
      - elasticsearch

  kibana:
    build: kibana/
    image: initiumlab/analytics-kibana:4.5.3-1
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
